#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void helloWorld()
{
	displayBigTextLine(1, "Hello World!");
	sleep(1000);
	eraseDisplay();
	sleep(1000);
}


task main()
{
	int i;
	for (i=0;i<5;i++)
	{

		helloWorld();
	}

}
