#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int Fib(int n)
{
	if (n==0) return 0;
	else if (n==1) return 1;
	else {
		return Fib(n-1)+Fib(n-2);
	}
}


task main()
{
	int i=0;
	int a[22];

	a[0] = 0;
	a[1] = 1;
	for (int j = 2;j<21;j++)
	{
		a[j] = a[j-1]+a[j-2];
	}
	for (int j=0;j<21;j++)
	{
		displayBigTextLine(6,"		     %d",a[j]);
	}


	while(i<20)
	{
		displayBigTextLine(6,"		     %d",Fib(i));
		sleep(1000);
		eraseDisplay();
		i++;
		if(i == 20) i=0;
	}



}
