#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void helloWorld()
{
	displayTextLine(1, "Hello World!");
	sleep(10000);
	eraseDisplay();
}

task main()
{

	helloWorld();

}
