#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnPoint(int time)
{
	setMotorSpeed(leftMotor, -20);
	setMotorSpeed(rightMotor, 20);
	sleep(time);
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}

void moveStraight(int time)
{
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);
	sleep(time);
}

void robotWalk()
{
	moveStraight(4000);
	turnPoint(1775);
	moveStraight(4000);
	turnPoint(1775);
}

task main()
{
	displayTextLine(6,"Start of the Program");
	sleep(2000);

	for (int i=0;i<5;i++)
	{
		eraseDisplay();
		displayTextLine(6,"The robot is executing");
		displayTextLine(7,"the turn %d", i);
		robotWalk();
		eraseDisplay();
	}

	displayTextLine(6,"End of the Program");
	sleep(2000);

}
