#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void turnPoint(int time)
{
	setMotorSpeed(leftMotor, -20);
	setMotorSpeed(rightMotor, 20);
	sleep(time);
}

task main()
{
	//for 360 turn is 3550
	//for 5 turn is 49
	//30 turn is 294
	//45 turn is 441
	//90 turn is 887
	//135 turn is 1323
	//the robot doens't execute precise turn. It needs "float" values do so.
	turnPoint(3550);


}
