#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float color = 0.0;

task sensing()
{
	while(1)
	{
		color = getColorReflected(S3);
		sleep(5);
	}
}

task drive()
{
	while(1)
	{
		if (color>=22.5 && color<=66.5)
		{
			setMotorSync(leftMotor,rightMotor,0,40);
			sleep(20);
		}
		else if (color<22.5)
		{
			setMotorSync(leftMotor,rightMotor, 80,20);
			sleep(3);
		}
		else if (color>66.5)
		{
			setMotorSync(rightMotor,leftMotor, 80,20);
			sleep(3);
		}
		sleep(10);
	}
}



task main()
{
	clearDebugStream();

	startTask(sensing);
	startTask(drive);

	while(1)
	{
		writeDebugStreamLine("Value is %d", getColorReflected(S3));
		sleep(1000);
	}
}
