#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string state = "idle";

void moveStraight(int time)
{
	setMotorSync(leftMotor,rightMotor,0,50);
	sleep(time);
}

task main()
{
	clearTimer(T1);
		while(1)
		{
			if (state == "idle")
			{
				moveStraight(4000);
				state = "forward";
			}
			if (state == "forward")
			{
				displayTextLine(1, "Time taken to turn is %d", getTimerValue(T1));
				break;
			}
		}
}
