#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


string state = "arm lowered";
int distanceToLine = 330;
float degrees = distanceToLine/176.0 * 360;
int count = 0;


void armlowered()
{
		displayBigTextLine(1,"Arm Lowered");
		writeDebugStreamLine("Arm Lowered");
		setMotorTarget(armMotor, -180, 75);
		sleep(1000);
		eraseDisplay();
			if (count == 2)
			{
				state = "turn";
			}
			else
			{
				state = "forward";
			}
}

void armraised()
{
	setMotorTarget(armMotor, 180, 75);
	displayBigTextLine(1,"Arm Raised");
	writeDebugStreamLine("Arm Raised");
	sleep(1000);
	eraseDisplay();
	state = "arm lowered";
}

void forward()
{
	setMotorTarget(leftMotor, degrees, 75);
	setMotorTarget(rightMotor, degrees, 75);
	sleep(2000);
	eraseDisplay();
	state = "arm raised";
}

void turn()
{
	displayBigTextLine(1,"Truning");
	writeDebugStreamLine("Turning");
	setMotorSync(leftMotor,rightMotor,100,20);
	sleep(1775);
	eraseDisplay();
	state = "backwards";

}

void goBack()
{
	displayBigTextLine(1,"Going back");
	writeDebugStreamLine("Going back");
	setMotorSync(leftMotor,rightMotor,0,50);
	sleep(4000);
	setMotorSync(leftMotor,rightMotor,0,50);
	sleep(1250);
	eraseDisplay();
	state = "Stop";
}


task main()
{
	displayBigTextLine(1, "Start");
	sleep(500);
	eraseDisplay();
	clearDebugStream();


	writeDebugStreamLine("degrees to line %d", degrees);

	//Lowering the arm
	if (state == "arm lowered")
	{
		armlowered();
	}

	while (1){

		displayBigTextLine(1,"Part %d", count+1);
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		writeDebugStreamLine("Going to next line, Part %d starting", count+1);
		if (state == "arm lowered")
	{
		armlowered();
	}

		//move robot to next line
		if (state == "forward")
		{
			forward();
		}
		//Arm Movement
		if (state == "arm raised")
		{
			armraised();
		}
		if(state == "arm lowered")
		{
			armlowered();
		}
		//Part
		count++;
		if (state == "turn")
		{
			turn();
		}
		if(state == "backwards")
		{
			goBack();
		}
		if(state == "Stop")
		{
			displayBigTextLine(1,"Task completed");
			writeDebugStreamLine("Task completed");
			break;
		}

	}

	displayBigTextLine(1,"End");
}
