#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int size = 5;
	//int origin = 5;
	int x = 6;
	int y = 6;
	int vx = rand()%7-3+5;
	int vy = rand()%7-3+5;
	drawEllipse(x-size, y+size, x+size, y-size);
	while(1)
	{
		sleep(1000);
		//origin = origin + vx;
		eraseEllipse(x-size, y+size, x+size, y-size);
		//x = x + vx;
		//y = y + vy;
		if (x-size + vx <= 0 || x+size+vx >= 177)
		{
			if (x-size + vx <= 0)
			{
				drawEllipse(0, y+size, size, y-size);
				sleep(1000);
				eraseEllipse(0, y+size, size, y-size);
			}
			if (x+size + vx <= 177)
			{
				drawEllipse(177-size, y+size, 177, y-size);
				sleep(1000);
				eraseEllipse(177-size, y+size, 177, y-size);
			}
			vx = -vx;
			x = x + vx;
			drawEllipse(x-size, y+size, x+size, y-size);
		}
		else if (y-size +vy <= 0 || y+size +vy >= 127)
		{
			if (y-size + vy <= 0)
			{
				drawEllipse(x-size, size, x+size, 0);
				sleep(1000);
				eraseEllipse(x-size, size, x+size, 0);
			}
			if (y+size + vy <= 127)
			{
				drawEllipse(x-size, 127, x+size, 127-size);
				sleep(1000);
				eraseEllipse(x-size, 127, x+size, 127-size);
			}
			vy = -vy;
			y = y + vy;
			drawEllipse(x-size, y+size, x+size, y-size);
		}
		else {
			x = x + vx;
			y = y + vy;
			drawEllipse(x-size, y+size, x+size, y-size);
		}

	}



}
