#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int sensorTouched = 0;
int motorspeed = 0;

task TouchSensorTask()
{
	while(1)
	{
		if (getTouchValue(touchSensor)==1)
		{
			sensorTouched = 1;
		}
		else
		{
			sensorTouched = 0;
		}
		sleep(5);
	}
}

task MotorTask()
{
	while(1)
	{
		while(sensorTouched == 0)
		{
			setMotorSpeed(leftMotor,15);
			setMotorSpeed(rightMotor,15);
			motorspeed = 15;
		}
		if (sensorTouched == 1)
		{
			setMotorSpeed(leftMotor,0);
			setMotorSpeed(rightMotor,0);
			motorspeed = 0;
		}
		sleep(5);
	}
}



task main()
{
	clearDebugStream();
	startTask(MotorTask);
	startTask(TouchSensorTask);
	while(1)
	{
		if(sensorTouched==0)
		{
			writeDebugStreamLine("The touch sensor was not touched and the speed is %d", motorspeed);
		}
		else
		{
			writeDebugStreamLine("The touch sensor was touched and the speed is 0");
		}
		sleep(5000);
	}


}
