#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int K = 1;
int target_dist = 0;
int motorspeed = 0;

task GyroSensorTask()
{
	resetGyro(S2);
	while(1)
	{
		int distanceLeft = abs(176 * (getMotorEncoder(leftMotor)/360));
		int e = target_dist-distanceLeft;
		motorspeed = K * e;
		sleep(20);
	}
}

task MotorTask()
{
	while(1)
	{
		while(motorspeed > 2)
		{
			//setMotorSpeed(leftMotor,motorspeed);
			//setMotorSpeed(rightMotor,-motorspeed);
			setMotorSync(leftMotor,rightMotor,0,motorspeed);
			//setMotorSync(motorB,motorC,0,motorspeed);
		}
		if(motorspeed<=0)
		{
			setMotorSync(motorB,motorC,0,0);
			motorspeed = 0;
		}
		sleep(30);
	}

}




task main()
{
	clearDebugStream();
	target_dist = 300;
	startTask(MotorTask);
	startTask(GyroSensorTask);

	while(1)
	{
		writeDebugStreamLine("the motorspeed is %d", motorspeed);
		sleep(1000);
	}


}
