#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lineNumber = 0;
string message;


task processMessage()
{
	lineNumber = 0;
	message = "Hi, I'm Ana";
	sleep(1000);
	while(1)
	{
		lineNumber = (lineNumber+1)%9;
		sprintf(message, "%d squared is %d", lineNumber, lineNumber*lineNumber);
		sleep(1000);
	}
}


task displayMessage()
{

		eraseDisplay();
		while(1)
		{
			eraseDisplay();
			displayTextLine(lineNumber,message);
			sleep(3000);
		}
}

task main()
{
		startTask(processMessage);
		startTask(displayMessage);
		while(1)
		{
			writeDebugStreamLine("%d is the lineNumber", lineNumber);
			writeDebugStreamLine("%s is the message", message);
			sleep(5000);
		}

}
