#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string state = "idle";

int K = 1;
int target_angle = 270;
int motorspeed = 0;

task GyroSensorTask()
{
	resetGyro(S2);
	while(1)
	{
		int e = target_angle-getGyroDegrees(S2);
		motorspeed = K * e;
		sleep(50);
	}
}

task MotorTask()
{
	while(1)
	{
		while(motorspeed != 0)
		{
			setMotorSync(motorB,motorC,100,motorspeed);
		}
		sleep(20);
	}

}

task main()
{
	clearTimer(T1);
	clearDebugStream();
		while(1)
		{
			if (state == "idle")
			{
				startTask(MotorTask);
				startTask(GyroSensorTask);
				while(1)
				{
					writeDebugStreamLine("the motorspeed is %d", motorspeed);
					sleep(500);
					if(motorspeed == 0)
						break;
				}
				state = "turn";
			}
			if (state == "turn")
			{

				displayTextLine(1, "Time taken to turn is %d", getTimerValue(T1));
				break;
			}
		}


}
