#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int prevRightMotorEncoder = 0;
int rightMotorEncoder = 0;
float wheelAngleChanged = 0;
float currentHeading = 0;
float x = 0;
float y = 0;


task PositionTrack()
{
	while(1)
	{
		prevRightMotorEncoder = rightMotorEncoder;
		rightMotorEncoder = getMotorEncoder(motorC);
		wheelAngleChanged = (rightMotorEncoder - prevRightMotorEncoder)*0.01745;
		currentHeading = (-1 * getGyroHeading(S2))* 0.01745;
		x = x+ 28* wheelAngleChanged* cos(currentHeading);
		y = y+ 28* wheelAngleChanged* sin(currentHeading);
		sleep(50);
	}
}


task main()
{
	startTask(PositionTrack);
	while(1)
	{
		sleep(50);
	}


}
