#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int theta = 0;
int x = 0;
int y = 0;

task forwardTask()
{
	while(1)
	{
		setMotorSync(leftMotor,rightMotor,0,20);
		sleep(20);

	}
}

task diagonalTask()
{
	while(1)
	{
		setMotorSync(leftMotor,rightMotor,-100,20);
		sleep(10);
		setMotorSync(leftMotor,rightMotor,0,0);
		sleep(10);
		setMotorSync(leftMotor,rightMotor,0,20);
		sleep(20);
	}
}


task turnTask()
{
	while(1)
	{
		setMotorSync(leftMotor,rightMotor,-100,20);
		sleep(20);
	}
}

task display()
{
	while(1)
	{
		displayTextLine(1,"Coordinates: (%d, %d, %d)", x, y, theta);
		writeDebugStreamLine("Coordinates: (%d, %d, %d)", x, y, theta);
		sleep(10);
	}
}



task main()
{
	clearDebugStream();
	while(1)
	{

		startTask(forwardTask);
		startTask(display);
		startTask(turnTask);
		startTask(diagonalTask);
		startTask(display);

		sleep(50);
	}
}
