#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int prevRightMotorEncoder = 0;
int rightMotorEncoder = 0;
float wheelAngleChanged = 0;
float currentHeading = 0;
float x = 0;
float y = 0;

int encoderCount = 1800;
int target_angle = 0;
int c = 0;
string state = "forward";
int motorspeed = 0;


task PositionTrack()
{
	while(1)
	{
		prevRightMotorEncoder = rightMotorEncoder;
		rightMotorEncoder = getMotorEncoder(motorC);
		wheelAngleChanged = (rightMotorEncoder - prevRightMotorEncoder)*0.01745;
		currentHeading = (-1 * getGyroHeading(S2))* 0.01745;
		x = x+ 28* wheelAngleChanged* cos(currentHeading);
		y = y+ 28* wheelAngleChanged* sin(currentHeading);
		sleep(50);
	}
}

task display()
{
	while(1)
	{
		displayTextLine(1,"Coordinates:");
		displayTextLine(2,"(%.2f, %.2f, %.2f)", x, y, currentHeading);
		writeDebugStreamLine("Coordinates: (%f, %f, %f)", x, y, currentHeading);
		sleep(10);
	}
}






void forward()
{
	resetMotorEncoder(leftMotor);
	if (c%2 == 0)
		encoderCount=1800;
	else
		encoderCount = 720;
	setMotorSyncEncoder(leftMotor,rightMotor,100,encoderCount,50);
	sleep(5000);
	c++;
	state = "turn";
}



void turn()
{
	while(1)
	{
		int e = target_angle-getGyroDegrees(S2);
		motorspeed = e;

		writeDebugStreamLine("!!!!!!!!!!!!!!MotorSpeed is %d", motorspeed);
		if(motorspeed < -1)
		{
			setMotorSync(leftMotor,rightMotor,100,motorspeed);

		}
		else
		{
			break;
		}
		sleep(50);
	}

	state = "forward";
}


task main()
{
	clearDebugStream();
	startTask(PositionTrack);

	while(1)
	{
		startTask(display);
		if(state == "forward")
		{
			writeDebugStreamLine("fwd");
			forward();
			sleep(10);
		}
		if(state == "turn")
		{
			target_angle = target_angle-90;
			writeDebugStreamLine("turn");
			turn();
		}
		if (c==4)
			break;
		sleep(50);
	}

}
